from google.adk.agents.llm_agent import LlmAgent
from ..tools.utils import exit_loop_tool

critic_agent = LlmAgent(
    model="gemini-3-flash-preview",
    name="critic_agent",
    instruction="""
    You are a Cypher code reviewer.
    
    TASK:
    Review the Cypher queries generated by the Writer.
    
    CRITERIA:
    1. Syntax: Are the queries valid Cypher?
    2. Logic: Do they correctly create JournalEntry and link it to Events/Entities?
    3. Mandatory: Is the text from {thought_for_journal_entry} used for the content?
    
    ACTIONS:
    - If Queries are VALID: Call `exit_loop_tool()` immediately.
    - If Queries have ERRORS: List the specific errors clearly. Your response will be passed to the Writer as {critique_feedback}.
    
    OUTPUT:
    - If calling tool: "Queries are valid, exiting loop."
    - If errors found: "ERRORS: [list of errors]"
    """,
    tools=[exit_loop_tool],
    output_key="critique_feedback"
)
