"""Harness and maintenance helpers for quality-plane version pinning."""

from .generation import (
    collect_harness_generation,
    get_or_pin_session_generation,
    load_session_pin,
    pin_session_generation,
    resolve_state_dir,
    write_active_harness_pin,
)
from .models import (
    HARNESS_SCHEMA_VERSION,
    MAINTENANCE_SCHEMA_VERSION,
    TAXONOMY_VERSION,
    ActivationAuthority,
    Decision,
    DreamRun,
    DreamStageReceipt,
    EvidenceSnapshot,
    Finding,
    HarnessGeneration,
    IllegalTransitionError,
    MaintenanceLease,
    Proposal,
    assert_legal_authority_transition,
    assert_legal_dream_stage_transition,
    assert_legal_owner_status_transition,
    assert_no_absorption_field,
    compute_generation_id,
    generation_request_fingerprint,
    is_legal_dream_stage_transition,
    stage_idempotency_key,
)

__all__ = [
    "HARNESS_SCHEMA_VERSION",
    "MAINTENANCE_SCHEMA_VERSION",
    "TAXONOMY_VERSION",
    "ActivationAuthority",
    "Decision",
    "DreamRun",
    "DreamStageReceipt",
    "EvidenceSnapshot",
    "Finding",
    "HarnessGeneration",
    "IllegalTransitionError",
    "MaintenanceLease",
    "Proposal",
    "assert_legal_authority_transition",
    "assert_legal_dream_stage_transition",
    "assert_legal_owner_status_transition",
    "assert_no_absorption_field",
    "collect_harness_generation",
    "compute_generation_id",
    "generation_request_fingerprint",
    "get_or_pin_session_generation",
    "is_legal_dream_stage_transition",
    "load_session_pin",
    "pin_session_generation",
    "resolve_state_dir",
    "stage_idempotency_key",
    "write_active_harness_pin",
]
